Questions controller created
MaxSandulsky/TestGuru pull request #12
Opened 2021-06-11 15:29 UTC by MaxSandulsky

2021-06-12 11:20 UTC, VidgarVii requested changes

2021-06-12 11:20 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    redirect_to test_questions_url
При создании и обновлении ресурса нужно проверять валидацию, которая была прописана в модели. И если валидация не прошла, то рендерят форму и выводит ошибки(ошибки будем показывать далее по уроку)
По этому тут надо условие записался ли объект в базу?
стандартный подход экшена create такой
```
@question = @test.questions.build(question_params)
if @question.save
  redirect_to @question
else
  render :new
end
```

2021-06-12 11:20 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    redirect_to test_questions_url
1 test_questions_path() Внутри проекта пользуйся относительными ссылками
2 хелпер `test_questions_path` требует передачи ему в аргументах объекта `test` или `id` соответсвующего объекта
если хелпер вызвать без аргументов, то рельсы могут сами поискать в памяти инстанс переменную с "подходящим" именем (`@test`) и передать ее в хелпер, если найдут
но пользоваться этой "магией" не стоит
гораздо правильней всегда в явном виде передавать в хелпер нужные ему аргументы

2021-06-12 11:20 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @question = Question.find_by!(id: params[:id])
Question.find(params[:id])

2021-06-12 11:20 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @test = Test.find_by!(id: params[:test_id])
Test.find(params[:test_id])

2021-06-12 11:20 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  before_action :test_by_id, only: %i[index new create]
есть rails way. Который надо придерживаться 
set_test
set_question

2021-06-13 20:04 UTC, VidgarVii requested changes

2021-06-13 20:04 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    logger.info('After destroy')
не волнуйся логи пишутся. Дополнительно логировать нет смысла

2021-06-13 20:04 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    redirect_to question_path(@question)
погоди. Так вопрос же будет удалён. Как откроется страница?

2021-06-15 02:17 UTC, MaxSandulsky commented on app/controllers/questions_controller.rb
> +    redirect_to question_path(@question)
Я тестирую во время написания, здесь отрабатывается исключение "вопрос не найден". Оставил так т.к. пока непонятно, а куда должно редиректить после удаления, наверное туда же, где можно было бы нажимать кнопку "удалить вопрос". Посмотрите пожалуйста ветку [develop](https://github.com/MaxSandulsky/TestGuru/pull/13), там Я добавил главную страницу и контроллер тестов, можно было бы либо на вопросы теста, либо на главную. Но сейчас Я не вижу альтернатив, т.к. запрос на удаление не передаёт в параметрах id теста, только вопроса: /questions/:id/delete

2021-06-15 02:26 UTC, MaxSandulsky commented on app/controllers/questions_controller.rb
> +    redirect_to question_path(@question)
Можно переписать маршрут:  get /tests/:id/questions/:id/delete, to: questions#destroy, это целесообразно?

2021-06-15 06:10 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    redirect_to question_path(@question)
так зачем нам экшен который выбрасывает исключение? Отправляй юзера куда хочешь. Главное чтобы не было 500 ошибки.
А лучше на страницу текущего теста
Кнопку добавишь в след уроке

2021-06-16 23:54 UTC, merged