Task 7
MaxSandulsky/TestGuru pull request #16
Opened 2021-06-19 04:52 UTC by MaxSandulsky

2021-06-19 04:59 UTC, MaxSandulsky commented on app/views/questions/_form.html.erb
> +<%= form_with model: [@question.test || @test, @question], local: true do |form| %>
Помогите пожалуйста исправить

2021-06-19 07:24 UTC, VidgarVii requested changes

2021-06-19 07:24 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  def index; end
важно:
ТЗ: "Список вопросов теста должен выводиться **на той же странице, что и сам тест**"
другими словами нужна страница для вывода теста
что приводит к следующим выводам:
- экшен `index` в классе `QuestionsController` лишний
- вызов коллбека для `index` не нужен
- список вопросов нужно выводить на странице теста
- путь `test_questions_path`, который ты используешь в экшенах, тоже лишний (нужно отменить его создание в `routes`)
- нужен контроллер для ресурса `:tests` (его написание было поэтапно продемонстрировано в скринкасте)

2021-06-19 07:24 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  def set_test
все методы  ниже сейчас считаются экшенами.
Надо обязательно добавить private

2021-06-19 07:24 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    params.require(:test).permit(:title, :level, :category_id).merge(author_id: 1)
я уже писал что хардкодить ид плохая идея

2021-06-19 07:24 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    params.require(:test).permit(:title, :level, :category_id).merge(author_id: 1)
автора лучше передаавть в экшене. Он нужен только при создании теста
И для этого лучше использовать интерфейс ассоциаций
author.own_tests.build()

2021-06-19 07:24 UTC, VidgarVii commented on app/helpers/footer_helper.rb
> +    link_to author, repo
ссылки на внешние ресурсы должны открывать в новой вкладке

2021-06-19 07:24 UTC, VidgarVii commented on app/helpers/questions_helper.rb
> +  end
для определения создается ресурс или редактируется
лучше использовать хелперы `.persisted?` или `.new_record?`

передавай в метод объект вопроса и по его состоянию ориентируйся что происходит (редактирование или создание)

2021-06-19 07:24 UTC, VidgarVii commented on app/helpers/tests_helper.rb
> +  end
очечь сомнительный хелпер

2021-06-19 07:24 UTC, VidgarVii commented on app/views/questions/_form.html.erb
> +<%= form_with model: [@question.test || @test, @question], local: true do |form| %>
просто пишешь `form_with model: [@test, @question]`
для эдит переменная `@test` будет пустая (не надо ее в контроллере искать, т.к. при использовании опции "шеллоу тру" в роутах для эдит `@test` не нужен)
соответсвенно в `@test` будет "нил" и рельсы построят правильный путь, потому что придет только `@question`
для нью придут оба объекта ("тест" и "квесшен") и рельсы также построят правильный путь

2021-06-21 06:06 UTC, VidgarVii requested changes

2021-06-21 06:06 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  #before_action :set_test, only: :edit
это мусор. Надо удалить

2021-06-21 06:06 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  before_action :set_question, only: :new
не делай колбек для одно экшена. Ухудшает читаемость

2021-06-21 06:06 UTC, VidgarVii commented on app/helpers/tests_helper.rb
> +    TEST_LEVELS[test.level] || 'Very hard'
TEST_LEVELS.fetch(level, 'Very hard)

2021-06-21 06:06 UTC, VidgarVii commented on app/views/tests/show.html.erb
> +<%= render 'questions/index' %>
render @test.questions

2021-06-22 06:57 UTC, merged