Task-8
MaxSandulsky/TestGuru pull request #19
Opened 2021-06-24 10:32 UTC by MaxSandulsky

test_passage model, controller, views added. New routes and functionality added

2021-06-24 15:11 UTC, VidgarVii requested changes

2021-06-24 15:11 UTC, VidgarVii commented on app/helpers/test_passages_helper.rb
> +
данные хелперы нужны для упрощение верстки сайта

2021-06-24 15:11 UTC, VidgarVii commented on app/models/test_passage.rb
> +    (correct_answers.empty? ? (return true) : (return false)) if answer_ids.nil?
correct_answers.empty? это вообще что-то странное для теста. У вопроса хотябы 1 ответ должен быть верным

2021-06-24 18:10 UTC, MaxSandulsky commented on app/controllers/tests_controller.rb
> +    return redirect_to tests_path if @test.invalid?(:use)
Так Я добавил в модель валидацию "validates :questions, presence: true, on: :use" чтобы нельзя было проходить тест если в нем нет вопросов

2021-06-24 18:14 UTC, MaxSandulsky commented on app/controllers/tests_controller.rb
> +    return redirect_to tests_path if @test.invalid?(:use)
Или лучше проверять наличие вопросов с помощью простой функции, а не валидации?

2021-06-25 08:15 UTC, VidgarVii requested changes

2021-06-25 08:15 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    return redirect_to tests_path if @test.invalid?(:use)
валидация моделей отвечает, за корректность данных перед записью в БД. Если объект не валиден. то и в БД он не попадёт.
То о чем ты говоришь, к валидации ни какого отношения не имеет. Да и поля questions у теста такого нет.
У тебя уже пахнет бизнес логикой. И её следует реализовывать методами. Вообще я вижу такое решение. Просто не показывать на странице тесты, у которых нет вопросов.

2021-06-25 08:15 UTC, VidgarVii commented on app/models/test_passage.rb
> +    test_passage_result > 85 ? 'green' : 'red'
1 лучше "магические цифры" хранить в константах с "говорящими именами"
например `SUCCESS_RATIO`
2 грин ред и пр. краски к модели ни какого отношения не имеет. Теперь у тебя то что должно быть во вью лежит в модели
сделай метод для `test_passage_result > 85` И вызывай его во вью

2021-06-25 08:15 UTC, VidgarVii commented on app/models/test_passage.rb
> +    test_passage_result > 85 ? 'Success' : 'Failure'
аналогично

2021-06-25 18:55 UTC, VidgarVii commented on app/models/test_passage.rb
> +  SUCCESS_RATIO = 85.freeze
цифры не над фризить

2021-06-25 21:19 UTC, merged