Task-9 complete
MaxSandulsky/TestGuru pull request #23
Opened 2021-06-27 10:24 UTC by MaxSandulsky

2021-06-27 10:51 UTC, MaxSandulsky commented on app/controllers/sessions_controller.rb
> +      cookies[:target_path] ? (redirect_to cookies[:target_path]) : (redirect_to tests_path) # With verb POST cookies don't work
Подскажите пожалуйста. Мой порядок действий: на странице с тестами, будучи залогиненым, удаляю куку сессии, кликаю на кнопку начала теста. Происходит редирект на login, но куки почему-то не обновляются. Как выяснилось, такое только с POST, если не упустил ничего. Большое спасибо!

2021-06-28 08:36 UTC, VidgarVii requested changes

2021-06-28 08:36 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :set_user, only: %i[create start]
нет смысла тут искать юзера, если у тебя уже есть метод current_user

2021-06-28 08:36 UTC, VidgarVii commented on app/helpers/footer_helper.rb
> +  def blank_url(author, repo)
уж больно странное название. При чем тут бланк?

2021-06-28 08:36 UTC, VidgarVii commented on app/helpers/footer_helper.rb
>      link_to author, repo, target: '_blank'
по идеи тут должна генерироваться ссылка на гитхаб

2021-06-28 08:36 UTC, VidgarVii commented on app/helpers/navigation_helper.rb
> +  end
все методы при не прохождении предусловия вернут нил. Очень плохая практика
пусть уж тогда будет такой код
if
else
end

А то помощь данных методов очень сомнительна

2021-06-28 08:36 UTC, VidgarVii commented on config/routes.rb
> +  get :logout, to: 'sessions#exit'
logout это удаление ресурса. Согласно CRUD и REST должен отправляться DELETE метод на экшен destroy

2021-06-28 08:36 UTC, VidgarVii commented on config/routes.rb
> +  resources :sessions, only: :create
тут ты создаешь 1 роут. А выше еще руками добавляешь 3 для данного контроллера сессий. Разберись с роутингом
С юзерами тоже самое

2021-06-28 10:42 UTC, MaxSandulsky commented on app/controllers/sessions_controller.rb
> +      cookies[:target_path] ? (redirect_to cookies[:target_path]) : (redirect_to tests_path) # With verb POST cookies don't work
https://stackoverflow.com/questions/68151162/ruby-on-rails-cant-set-cookies-in-some-actions

2021-06-28 13:56 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +      cookies[:target_path] ? (redirect_to cookies[:target_path]) : (redirect_to tests_path) # With verb POST cookies don't work
redirect_to cookies[:target_path] || tests_path

2021-06-28 13:56 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    redirect_to tests_path and return if @test.questions.empty?
в контроллерах ни каких return! может выбраситься 500
если redirect_to отработает. то код ниже не будет работать

2021-06-28 20:28 UTC, merged