Task-11 controller and model for gists
MaxSandulsky/TestGuru pull request #26
Opened 2021-07-01 21:04 UTC by MaxSandulsky

2021-07-02 07:15 UTC, VidgarVii requested changes

2021-07-02 07:15 UTC, VidgarVii commented on Gemfile
> +gem 'faraday'
faraday больше не используется. МОжно удалять

2021-07-02 07:15 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +  def gist
Gist это модель. Значит согласно rails way для записи в БД объекта Gist должен быть отдельный контроллер с экшеном create

2021-07-02 07:15 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    result = GistQuestionService.new(@test_passage.current_question, GITHUB_TOKEN).call
GITHUB_TOKEN можно сразу использовать в сервисе. передавать через контроллер не стоит

2021-07-02 07:15 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    flash_options = if result.nil?
nil плохая практика.
результат работы есть всегда. Есть стандартная практика использовать метод success?
т.е. тут должно быть
```
if result.success?
  ...
```

2021-07-02 07:15 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +                      { notice: "#{t('.success')} #{result[:html_url]}".html_safe }
от куда берется html_url? в сервисе про него нет ни слово.
Пусть сервис возвращает такой объект, который содержит все нужные данные и методы. И конечно этот объект должен быть объявлен явно

2021-07-02 07:15 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    @gist = Gist.create(user: current_user, url: result[:html_url], question: @test_passage.current_question)
тут мы не проверяем записался ли гист в базу. По этому лучше использовать bang метод

2021-07-02 07:15 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  end
ще можно так:
```ruby
[@question.body, *@question.answers.pluck(:body)].join("\n")
```

2021-07-02 07:15 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  def initialize(question, github_token, client: nil)
ты ни как не используешь параметр client: И не будешь испльзовать. Можно удалить

2021-07-02 07:15 UTC, VidgarVii commented on app/views/admin/gists/index.html.erb
> +  <% end %>
ни каких all ни каких each во вью.
Потом под дня потратишь в поисках, почему страница долго грузится.
Толькок контроллер передаёт данные во вью
render умеет работать с коллекциями

2021-07-02 10:04 UTC, MaxSandulsky commented on app/controllers/test_passages_controller.rb
> +    flash_options = if result.nil?
1 Я не могу найти определение метода success? для Sawyer::Resource
2 result.success? возвращает nil при успешном создании, потому что такого метода нет (скриншот)
3 при возникновении ошибки, например если токен не действителен, возникает исключение Octokit::Unauthorized в методе call, там Я обработал его, чтобы при неудаче возвращался nil, а не исключение.
![Screenshot from 2021-07-02 01-22-54](https://user-images.githubusercontent.com/78658094/124258354-f7148980-db35-11eb-9c24-db5d80e2549a.png)

2021-07-02 10:10 UTC, MaxSandulsky commented on app/controllers/test_passages_controller.rb
> +                      { notice: "#{t('.success')} #{result[:html_url]}".html_safe }
Я ничего не трогал, вот Octokit создаёт объект клиента и в нём уже есть "html_url"
![Screenshot from 2021-07-02 13-07-44](https://user-images.githubusercontent.com/78658094/124259052-c41ec580-db36-11eb-81e0-ace05f09699f.png)

2021-07-02 14:35 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  rescue Octokit::Unauthorized
а как мы узнаем, что октокит настрое правильно?
метод call должен вернуть ОБЪЕКТ, который должен содержать все нужные данные. 
Этот объект тебе надо самим создать. Например через Struct https://ruby-doc.org/core-2.5.0/Struct.html
т.е. тут должно быть что-то такого

```
def call
  result  = @client.create_gist(gist_params)
  ResultStruct.new(.....)
end
```

2021-07-03 14:39 UTC, VidgarVii requested changes

2021-07-03 14:39 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +  end
уже много раз говорил, что колбек для 1 экшена плохая идея

2021-07-03 14:39 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  rescue Octokit::Unauthorized
т.е. в твоём случаи не важно будет ли создан гист в гитхаб. 
у ResultStruct  success всегда будет true. 
отлавливать Octokit::Unauthorized  и ни как не обрабатывать этот случай плохая идея. Я уже писал, что там ты не узнаешь о причине не создания гиста.
Как пльзоваться ResultStructопять же не понятно. Где методы получания урла гист? Где хеш? success вообще не понятен. И назван не верно. методы предикаты должны всегда иметь знак ? в конце имени
Это success надо проверять явно и ставить в true только убедившись что гист в гитхаб был создан. Octokit::Unauthorized это не единственная причина почему гист может быть не создан. Причин может быть много. И завтра может появиться еще. Всё не отловишь

2021-07-03 14:39 UTC, VidgarVii commented on app/views/gists/_gist.html.erb
> +  <td><a href="<%= admin_question_path(gist.question) %>" target="_blank" maxlength="25"><%= gist.question.body %></a></td>
1 для ссылок используй link_to
2 для сокращения текста есть хелпер truncate` - [вот небольшой пост про него](https://makandracards.com/makandra/53287-heads-up-rails-offers-two-similar-means-for-text-truncation)

2021-07-03 14:39 UTC, VidgarVii commented on app/views/gists/index.html.erb
> +  <tr>
тут не хватает thead

2021-07-05 11:26 UTC, merged