Task-3
MaxSandulsky/TestGuru pull request #6
Opened 2021-05-27 05:39 UTC by MaxSandulsky

Required class and instance methods added
Seed created

2021-05-27 17:45 UTC, VidgarVii requested changes

2021-05-27 17:45 UTC, VidgarVii commented on app/models/test.rb
> +  end
запросы будет правильно решить через джойн таблиц
то как ты делаешь - это "решение в лоб"
оно работает, но оно скажем мягко "не оптимальное"

рельсы многие запросы могут сами оптимизировать в итоге и, к примеру, составить автоматически из двух запросов один, но полагаться на это не стоит
в реальной жизни такие запросы, как у тебя получились, писать не нужно

плюс мы сейчас пытаемся разобраться с тем, как работают ассоциации в рельсах, чтобы в дальнейшем было понимание того "что же они делают" и "как это работает", так вот рельсы точно не пишут такие запросы, конечно же все оптимизировано
посмотри предыдущее задание - там были (в части по скуль запросам) селекты с джойнами таблиц

здесь нужно в обоих методах решить все с помощью `joins` и `where` (в одно обращение к базе, один запрос)
пострайся разобраться - это важно и полезно

2021-05-27 17:45 UTC, VidgarVii commented on app/models/user.rb
> +  end
есть таблица "юзерс", есть таблица "тестс"
на втором занятии разбирались со списком сущностей и там упоминалась сущность "результаты" (или как-то еще могли назвать, не помню как конкретно у тебя получилось)
таблица "результаты" должна быть связующей между "юзерс" и "тестс"
когда "юзер" проходит "тест" в ней должна появляться запись
это так называемая связующая таблица
мне кажется в скринкастах упоминались связующие таблицы
но в любом случае можешь поискать объяснения, документацию в интернете
минимальная связующая таблица должна содержать 3 поля: ай-ди (собственное), ай-ди первой таблицы, ай-ди второй таблицы (т.е. праймари ключ и два внешних ключа)
вот с помощью такой таблицы будет правильно решать данную задачку

2021-05-27 17:45 UTC, VidgarVii commented on db/seeds.rb
> +Question.create([{ test_id: 1, body: 'In Ruby, everything is ...' },
лучше использовать `create!` - метод бросит исключение, если запись не создастся
сразу будет видно, если что-то пошло не так

2021-05-28 19:59 UTC, VidgarVii commented on db/seeds.rb
> +Question.create([{ test_id: 1, body: 'In Ruby, everything is ...' },
"хардкодить" `id` - не очень хорошая затея
такой "сид" невозможно накатить на существующую базу, ведь там id могут быть заняты другими записями или вовсе отсутствовать
правильней воспользоваться тем, что метод `create` возвращает созданные записи

2021-05-31 12:26 UTC, VidgarVii requested changes

2021-05-31 12:26 UTC, VidgarVii commented on app/models/answer.rb
> +  belongs_to :question
с ассоциациями ты поторопился, это будет чуть дальше в курсе
в этом задании нужно реализовать запросы через SQL без использования ассоциаций - суть урока - понять какую работу делает за нас `ActiveRecord` (и для этого нужно здесь выполнить ее самому)

2021-05-31 12:26 UTC, VidgarVii commented on app/models/user.rb
> +    test_passed.order(:id).where(level: level)
тут сортировка лишняя

2021-05-31 12:26 UTC, VidgarVii commented on db/migrate/20210521015108_create_questions.rb
> +      t.references :test, null: false
foreign_key отвечают за целостность данных. Их нельзя удалять

2021-06-01 09:27 UTC, VidgarVii commented on db/seeds.rb
> +ptests = PassedTest.create!([{ user_id: users[0].id, test_id: tests[0].id },
ptests переменная не используется. Лучше удалить

2021-06-01 09:34 UTC, MaxSandulsky commented on db/seeds.rb
> +ptests = PassedTest.create!([{ user_id: users[0].id, test_id: tests[0].id },
Исправил

2021-06-01 09:35 UTC, merged